//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gastos.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n                    <ArrayOfString xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-" +
            "instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n                       " +
            " <string>Almacen</string>\r\n\t\t\t            <string>Almuerzo</string>\r\n           " +
            "             <string>Apple Tv</string>\r\n                        <string>Carnicer" +
            "ía</string>\r\n                        <string>Claro</string>\r\n                   " +
            "     <string>Consolidación</string>\r\n                        <string>Delivery</s" +
            "tring>\r\n                        <string>Disney+</string>\r\n                      " +
            "  <string>Edesur</string>\r\n                        <string>Expensas</string>\r\n  " +
            "                      <string>Farmacia</string>\r\n                        <string" +
            ">Fiambrería</string>\r\n\t\t\t            <string>Flow</string>\r\n                    " +
            "    <string>Gatas</string>\r\n                        <string>Impuesto Municipal</" +
            "string>\r\n                        <string>Luna</string>\r\n                        " +
            "<string>Mercadolibre</string>\r\n                        <string>Metrogas</string>" +
            "\r\n                        <string>Netflix</string>\r\n                        <str" +
            "ing>Otros</string>\r\n                        <string>Pescadería</string>\r\n       " +
            "                 <string>Prime Video</string>\r\n                        <string>S" +
            "alida</string>\r\n                        <string>Seguro Hogar</string>\r\n         " +
            "               <string>Spotify</string>\r\n                        <string>Superme" +
            "rcado</string>\r\n                        <string>Verdulería</string>\r\n           " +
            "         </ArrayOfString>\r\n                ")]
        public string Categorias {
            get {
                return ((string)(this["Categorias"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G:\\My Drive")]
        public string Carpeta {
            get {
                return ((string)(this["Carpeta"]));
            }
            set {
                this["Carpeta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gastos.xlsm")]
        public string Archivo {
            get {
                return ((string)(this["Archivo"]));
            }
            set {
                this["Archivo"] = value;
            }
        }
    }
}
